package com.ecommerce.akinjides.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import java.math.BigDecimal;

import static javax.persistence.GenerationType.IDENTITY;

//Lombok and spring annotations for constructors and mapping to database table
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "products")
public class Product {
    @Id //sets primary key for table
    @GeneratedValue(strategy = IDENTITY) //sets primary key generation strategy to Identity which means it will be
//    generated by the database id column
    private Long productId;
    private String category;
    private String productName;
    private BigDecimal price;
    private String image;

}
