package com.ecommerce.akinjides.repository;

import com.ecommerce.akinjides.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductRepo extends JpaRepository<Product, Long> {

//    The ProductRepo interface extends JpaRepository and specifies that
//    it works with the Product entity and its primary key type (Long).
//    By extending JpaRepository, the ProductRepo interface inherits all
//    of the common database operations provided by JpaRepository. (CRUD)

//    This interface serves as a contract for defining the methods that
//    can be used to interact with the database for the Product entity.
//    The methods in this interface can be automatically generated by
//    Spring Data JPA, based on their method signatures, and can be used
//    to perform various database operations such as saving a new Product,
//    deleting an existing Product, or retrieving a list of all Product
//    entities.




}
